table cohort_retention
	lineageTag: ab7bb588-be6b-42fa-82cf-3abf79e14ca2

	measure 'Month-1 Retention' = DIVIDE(SUM(cohort_retention[customers_active_month_1]), SUM(cohort_retention[cohort_size])) * 100
		formatString: 0.00\%
		displayFolder: Retention
		lineageTag: 478f18af-4e08-4d47-80d0-4754fa8b62e9

	measure 'Month-2 Retention' = DIVIDE(SUM(cohort_retention[customers_active_month_2]), SUM(cohort_retention[cohort_size])) * 100
		formatString: 0.00\%
		displayFolder: Retention
		lineageTag: 03309f94-d1a0-4b8a-a525-e3087620df10

	measure 'Median Month-1 Retention' = MEDIANX(ALL(cohort_retention), cohort_retention[retention_month_1_pct])
		formatString: 0.00\%
		displayFolder: Retention
		lineageTag: 8aef976c-fd39-4d01-bd3f-3ba1d82e9fb5

	column cohort_month
		dataType: dateTime
		formatString: Long Date
		lineageTag: fbbb59d4-9316-4c42-b61d-acdadf581fa7
		summarizeBy: none
		sourceColumn: cohort_month

		variation Variation
			isDefault
			relationship: c41f9007-fb30-4b69-bd6a-eda2759d3d74
			defaultHierarchy: LocalDateTable_6e23a0d5-bddd-4a09-839b-4ea82e35fc7e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column cohort_size
		dataType: int64
		formatString: 0
		lineageTag: c8098c42-a703-4c77-97bf-d17fe34a9667
		summarizeBy: sum
		sourceColumn: cohort_size

		annotation SummarizationSetBy = Automatic

	column customers_active_month_1
		dataType: int64
		formatString: 0
		lineageTag: f96834e5-c8f9-4b26-92b8-d543ecea6ccb
		summarizeBy: sum
		sourceColumn: customers_active_month_1

		annotation SummarizationSetBy = Automatic

	column retention_month_1_pct
		dataType: double
		lineageTag: a6194583-0b02-4c0c-b9af-8ade71eb3e14
		summarizeBy: sum
		sourceColumn: retention_month_1_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column customers_active_month_2
		dataType: int64
		formatString: 0
		lineageTag: fa25172a-5abb-4dfa-81a1-2648e04782cd
		summarizeBy: sum
		sourceColumn: customers_active_month_2

		annotation SummarizationSetBy = Automatic

	column retention_month_2_pct
		dataType: double
		lineageTag: e7b7274d-fb7c-4e2e-9909-0897c72c21c7
		summarizeBy: sum
		sourceColumn: retention_month_2_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cohort Label' = FORMAT(cohort_retention[cohort_month], "mmm yy")
		dataType: string
		displayFolder: Retention
		lineageTag: 2ca38c8a-bff4-4659-9746-40e01017ecf3
		summarizeBy: none
		sortByColumn: cohort_month

	partition cohort_retention = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\04ama\OneDrive\job-hunt\portfolio-projects\Ecommerce-growth-analytics\Dashboard\exports\cohort_retention.csv"), [Delimiter = ",", Columns = 6, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"cohort_month", type date}, {"cohort_size", Int64.Type}, {"customers_active_month_1", Int64.Type}, {"retention_month_1_pct", type number}, {"customers_active_month_2", Int64.Type}, {"retention_month_2_pct", type number}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

