table funnel
	lineageTag: d88c2eac-2fc9-4a77-a60d-b85f81cdf465

	measure 'Orders Reached' = SUM(funnel[orders_reached])
		formatString: #,##0
		displayFolder: Funnel
		lineageTag: ad560962-9bc9-47bf-9724-13a46993d6ca

	measure 'Pct of Total' = SUM(funnel[pct_of_total])
		formatString: 0.00\%
		displayFolder: Funnel
		lineageTag: 7560b3e5-e02b-4234-9960-3b654efeb9ed

	measure 'Funnel Stage Color' =
			
			VAR StageLower = LOWER(SELECTEDVALUE(funnel[stage]))
			RETURN
			SWITCH(
			    TRUE(),
			    StageLower = "purchased", "#86B6EF",
			    StageLower = "approved", "#5598E7",
			    StageLower = "shipped", "#2A78D6",
			    StageLower = "delivered", "#1C5CAB",
			    "#86B6EF"
			)
		isHidden
		displayFolder: Funnel
		lineageTag: eb7b5a29-9b6e-4399-834c-d99e56623d06

	column stage
		dataType: string
		lineageTag: d93321f1-768b-4696-b634-dafbffcc74e3
		summarizeBy: none
		sourceColumn: stage

		annotation SummarizationSetBy = Automatic

	column orders_reached
		dataType: int64
		formatString: 0
		lineageTag: 706b5f47-b1a5-404d-971f-4c04396ac51b
		summarizeBy: sum
		sourceColumn: orders_reached

		annotation SummarizationSetBy = Automatic

	column pct_of_total
		dataType: double
		lineageTag: ec80fe94-3982-4baa-a65b-826fd264d877
		summarizeBy: sum
		sourceColumn: pct_of_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Stage Label' =
			SWITCH(
			    TRUE(),
			    LOWER(funnel[stage]) = "purchased", "Purchased",
			    LOWER(funnel[stage]) = "approved", "Approved",
			    LOWER(funnel[stage]) = "shipped", "Shipped",
			    LOWER(funnel[stage]) = "delivered", "Delivered",
			    funnel[stage]
			)
		dataType: string
		displayFolder: Funnel
		lineageTag: 6a0f9265-3f52-42e6-bcb6-ab15bbdbbced
		summarizeBy: none

	partition funnel = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\04ama\OneDrive\job-hunt\portfolio-projects\Ecommerce-growth-analytics\Dashboard\exports\funnel.csv"), [Delimiter = ",", Columns = 3, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"stage", type text}, {"orders_reached", Int64.Type}, {"pct_of_total", type number}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

