table kpi_overview
	lineageTag: 67fbefc6-ebde-47ab-8d14-27709b3f8f07

	measure 'KPI Overview Row' =
			
			VAR TotalOrders = SELECTEDVALUE(kpi_overview[total_orders])
			VAR TotalCustomers = SELECTEDVALUE(kpi_overview[total_unique_customers])
			VAR AOV = SELECTEDVALUE(kpi_overview[avg_order_value])
			VAR RepeatRate = SELECTEDVALUE(kpi_overview[repeat_purchase_rate_pct])
			VAR TileCSS = "background:#fcfcfb;border:1px solid rgba(11,11,11,.10);border-radius:10px;padding:16px 18px;box-shadow:0 1px 2px rgba(11,11,11,.06),0 6px 20px rgba(11,11,11,.07);font-family:'Segoe UI',system-ui,sans-serif;"
			VAR LabelCSS = "font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:#52514e;"
			VAR ValueCSS = "font-size:26px;font-weight:600;letter-spacing:-.01em;color:#0b0b0b;margin-top:6px;"
			VAR CaptionCSS = "font-size:12px;color:#898781;margin-top:4px;"
			VAR Tile1 = "<div style='" & TileCSS & "'><div style='" & LabelCSS & "'>Total Orders</div><div style='" & ValueCSS & "'>" & FORMAT(TotalOrders,"#,##0") & "</div></div>"
			VAR Tile2 = "<div style='" & TileCSS & "'><div style='" & LabelCSS & "'>Unique Customers</div><div style='" & ValueCSS & "'>" & FORMAT(TotalCustomers,"#,##0") & "</div></div>"
			VAR Tile3 = "<div style='" & TileCSS & "'><div style='" & LabelCSS & "'>Avg. Order Value</div><div style='" & ValueCSS & "'>R$" & FORMAT(AOV,"#,##0.00") & "</div></div>"
			VAR Tile4 = "<div style='" & TileCSS & "'><div style='" & LabelCSS & "'>Repeat Purchase Rate</div><div style='" & ValueCSS & "'>" & FORMAT(RepeatRate,"0.0") & "%</div><div style='" & CaptionCSS & "'>of customers order again</div></div>"
			RETURN
			"<div style='display:flex;gap:14px;'>" & Tile1 & Tile2 & Tile3 & Tile4 & "</div>"
		lineageTag: 30817776-a22c-48b7-ae5e-eac1bb5e5236

	measure 'KPI Row - Model Metrics' =
			
			VAR RocAuc = CALCULATE(SELECTEDVALUE(repeat_purchase_model_metrics[roc_auc]), repeat_purchase_model_metrics[interaction_terms] = FALSE)
			VAR PrAuc = CALCULATE(SELECTEDVALUE(repeat_purchase_model_metrics[pr_auc]), repeat_purchase_model_metrics[interaction_terms] = FALSE)
			VAR BaseRate = CALCULATE(SELECTEDVALUE(repeat_purchase_model_metrics[base_rate]), repeat_purchase_model_metrics[interaction_terms] = FALSE)
			VAR Top10 = CALCULATE(SELECTEDVALUE(repeat_purchase_model_metrics[top_10pct_capture_rate]), repeat_purchase_model_metrics[interaction_terms] = FALSE)
			VAR Top20 = CALCULATE(SELECTEDVALUE(repeat_purchase_model_metrics[top_20pct_capture_rate]), repeat_purchase_model_metrics[interaction_terms] = FALSE)
			VAR Top10Lift = DIVIDE(Top10, 0.1)
			VAR Top20Lift = DIVIDE(Top20, 0.2)
			VAR TileCSS = "background:#fcfcfb;border:1px solid rgba(11,11,11,.10);border-radius:10px;padding:20px 22px;box-shadow:0 1px 2px rgba(11,11,11,.06),0 6px 20px rgba(11,11,11,.07);font-family:'Segoe UI',system-ui,sans-serif;"
			VAR LabelCSS = "font-size:12px;text-transform:uppercase;letter-spacing:.06em;color:#52514e;"
			VAR ValueCSS = "font-size:30px;font-weight:600;letter-spacing:-.01em;color:#0b0b0b;margin-top:6px;"
			VAR CaptionCSS = "font-size:13px;color:#898781;margin-top:4px;"
			VAR GoodCaptionCSS = "font-size:13px;color:#006300;font-weight:600;margin-top:4px;"
			VAR Tile1 = "<div style='" & TileCSS & "'><div style='" & LabelCSS & "'>ROC-AUC</div><div style='" & ValueCSS & "'>" & FORMAT(RocAuc,"0.000") & "</div><div style='" & CaptionCSS & "'>vs 0.500 random</div></div>"
			VAR Tile2 = "<div style='" & TileCSS & "'><div style='" & LabelCSS & "'>PR-AUC</div><div style='" & ValueCSS & "'>" & FORMAT(PrAuc,"0.000") & "</div><div style='" & CaptionCSS & "'>vs " & FORMAT(BaseRate,"0.0%") & " base rate</div></div>"
			VAR Tile3 = "<div style='" & TileCSS & "'><div style='" & LabelCSS & "'>Top-10% Capture Rate</div><div style='" & ValueCSS & "'>" & FORMAT(Top10,"0.0%") & "</div><div style='" & GoodCaptionCSS & "'>" & FORMAT(Top10Lift,"0.0") & "× lift over random</div></div>"
			VAR Tile4 = "<div style='" & TileCSS & "'><div style='" & LabelCSS & "'>Top-20% Capture Rate</div><div style='" & ValueCSS & "'>" & FORMAT(Top20,"0.0%") & "</div><div style='" & GoodCaptionCSS & "'>" & FORMAT(Top20Lift,"0.0") & "× lift over random</div></div>"
			RETURN
			"<div style='display:flex;gap:16px;'>" & Tile1 & Tile2 & Tile3 & Tile4 & "</div>"
		lineageTag: b955737c-8dcd-4e19-bfdb-0056eaaa2ce4

	column total_orders
		dataType: int64
		formatString: 0
		lineageTag: 58556962-310d-451e-a71a-29bdac09bb04
		summarizeBy: sum
		sourceColumn: total_orders

		annotation SummarizationSetBy = Automatic

	column total_unique_customers
		dataType: int64
		formatString: 0
		lineageTag: 30959efd-e140-45da-b450-b3a153ad6332
		summarizeBy: sum
		sourceColumn: total_unique_customers

		annotation SummarizationSetBy = Automatic

	column avg_order_value
		dataType: double
		lineageTag: 943a33f4-3652-42cd-8c72-33dc443e4e34
		summarizeBy: sum
		sourceColumn: avg_order_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column repeat_purchase_rate_pct
		dataType: double
		lineageTag: a359e7fd-bff4-4dc5-a1bb-94e134f4b2a4
		summarizeBy: sum
		sourceColumn: repeat_purchase_rate_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition kpi_overview = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\04ama\OneDrive\job-hunt\portfolio-projects\Ecommerce-growth-analytics\power_bi\exports\kpi_overview.csv"), [Delimiter = ",", Columns = 4, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"total_orders", Int64.Type}, {"total_unique_customers", Int64.Type}, {"avg_order_value", type number}, {"repeat_purchase_rate_pct", type number}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

