table kpi_overview
	lineageTag: 67fbefc6-ebde-47ab-8d14-27709b3f8f07

	measure 'Total Orders' = SUM(kpi_overview[total_orders])
		formatString: #,##0
		displayFolder: Overview
		lineageTag: b15cf90e-1adc-4b81-bf3c-2e5bc8cbf3f1

	measure 'Unique Customers' = SUM(kpi_overview[total_unique_customers])
		formatString: #,##0
		displayFolder: Overview
		lineageTag: b779fc75-4652-4a96-9d51-c7fb4efe4a0c

	measure 'Avg Order Value' = SUM(kpi_overview[avg_order_value])
		formatString: R$#,##0.00
		displayFolder: Overview
		lineageTag: 45c28c95-98a8-4e36-902c-882ebdb290f4

	measure 'Repeat Purchase Rate' = SUM(kpi_overview[repeat_purchase_rate_pct])
		formatString: 0.0\%
		displayFolder: Overview
		lineageTag: b7764e98-18c6-4066-b32f-69802f225016

	column total_orders
		dataType: int64
		formatString: 0
		lineageTag: 58556962-310d-451e-a71a-29bdac09bb04
		summarizeBy: sum
		sourceColumn: total_orders

		annotation SummarizationSetBy = Automatic

	column total_unique_customers
		dataType: int64
		formatString: 0
		lineageTag: 30959efd-e140-45da-b450-b3a153ad6332
		summarizeBy: sum
		sourceColumn: total_unique_customers

		annotation SummarizationSetBy = Automatic

	column avg_order_value
		dataType: double
		lineageTag: 943a33f4-3652-42cd-8c72-33dc443e4e34
		summarizeBy: sum
		sourceColumn: avg_order_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column repeat_purchase_rate_pct
		dataType: double
		lineageTag: a359e7fd-bff4-4dc5-a1bb-94e134f4b2a4
		summarizeBy: sum
		sourceColumn: repeat_purchase_rate_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition kpi_overview = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\04ama\OneDrive\job-hunt\portfolio-projects\Ecommerce-growth-analytics\Dashboard\exports\kpi_overview.csv"), [Delimiter = ",", Columns = 4, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"total_orders", Int64.Type}, {"total_unique_customers", Int64.Type}, {"avg_order_value", type number}, {"repeat_purchase_rate_pct", type number}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

