table repeat_purchase_odds_ratios
	lineageTag: e65f7535-9cb9-431e-b42f-2b5c90e69cf4

	measure 'Odds Ratio Color' = IF(SELECTEDVALUE(repeat_purchase_odds_ratios[odds_ratio]) >= 1, "#2A78D6", "#E34948")
		displayFolder: Model
		lineageTag: 2782fd8e-48b1-49c3-9b94-55b4b00ee94a

	measure 'Odds Ratio Show Row' =
			
			VAR SelectedN = SELECTEDVALUE('Top Bottom N'[N Value], 5)
			VAR CurrentOR = SELECTEDVALUE(repeat_purchase_odds_ratios[odds_ratio])
			VAR HigherRank =
			    RANKX(FILTER(ALLSELECTED(repeat_purchase_odds_ratios), repeat_purchase_odds_ratios[odds_ratio] >= 1), repeat_purchase_odds_ratios[odds_ratio], CurrentOR, DESC, DENSE)
			VAR LowerRank =
			    RANKX(FILTER(ALLSELECTED(repeat_purchase_odds_ratios), repeat_purchase_odds_ratios[odds_ratio] < 1), repeat_purchase_odds_ratios[odds_ratio], CurrentOR, ASC, DENSE)
			RETURN
			IF(
			    SelectedN >= 999 ||
			    (CurrentOR >= 1 && HigherRank <= SelectedN) ||
			    (CurrentOR < 1 && LowerRank <= SelectedN),
			    1
			)
		formatString: 0
		isHidden
		displayFolder: Model
		lineageTag: e5f60be3-c578-4e7a-a958-7a382934c4bc

	column feature
		dataType: string
		lineageTag: 74a28ad4-fbba-487d-9571-64d3bb021df4
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = Automatic

	column coefficient
		dataType: double
		lineageTag: 37932501-7d82-4b47-8249-eb57e2e30f9f
		summarizeBy: sum
		sourceColumn: coefficient

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column odds_ratio
		dataType: double
		lineageTag: a1365580-d8a3-4156-9ed0-b22fc4530268
		summarizeBy: sum
		sourceColumn: odds_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column abs_coefficient
		dataType: double
		lineageTag: 4cd5a51b-c1a0-48ca-8f08-145efae0cf44
		summarizeBy: sum
		sourceColumn: abs_coefficient

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column direction
		dataType: string
		lineageTag: 24a32f9e-040e-4a9d-9f7f-7c4343b9e0d1
		summarizeBy: none
		sourceColumn: direction

		annotation SummarizationSetBy = Automatic

	column model
		dataType: string
		lineageTag: 8579646c-a219-44ca-b52c-a86f1f207fa0
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	column run_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 318a9293-e034-49ed-9ef0-5c10712e2e0d
		summarizeBy: none
		sourceColumn: run_at

		variation Variation
			isDefault
			relationship: e7bf653c-a063-452a-be0c-5efc78db2171
			defaultHierarchy: LocalDateTable_87ad67a9-7d57-47d1-9a42-6a36596dd803.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column git_commit
		dataType: string
		lineageTag: 458f52a2-c2b1-477c-87ea-9943bd88f49f
		summarizeBy: none
		sourceColumn: git_commit

		annotation SummarizationSetBy = Automatic

	column 'Feature Type' =
			SWITCH(
			    TRUE(),
			    LEFT(repeat_purchase_odds_ratios[feature], 15) = "customer_state_", "Customer state",
			    LEFT(repeat_purchase_odds_ratios[feature], 17) = "product_category_", "Product category",
			    LEFT(repeat_purchase_odds_ratios[feature], 13) = "payment_type_", "Payment type",
			    "Other"
			)
		dataType: string
		displayFolder: Model
		lineageTag: 336b5cfb-80e4-496d-86fb-328e3b860069
		summarizeBy: none

	column 'Feature Label' =
			VAR RawFeature = repeat_purchase_odds_ratios[feature]
			VAR NoPrefix =
			    SWITCH(
			        TRUE(),
			        LEFT(RawFeature, 15) = "customer_state_", MID(RawFeature, 16, 100),
			        LEFT(RawFeature, 17) = "product_category_", MID(RawFeature, 18, 100),
			        LEFT(RawFeature, 13) = "payment_type_", MID(RawFeature, 14, 100),
			        RawFeature
			    )
			VAR Spaced = TRIM(SUBSTITUTE(NoPrefix, "_", " "))
			VAR PathText = SUBSTITUTE(Spaced, " ", "|")
			VAR WordCount = PATHLENGTH(PathText)
			VAR W1 = PATHITEM(PathText, 1)
			VAR W2 = IF(WordCount >= 2, PATHITEM(PathText, 2), "")
			VAR W3 = IF(WordCount >= 3, PATHITEM(PathText, 3), "")
			VAR W4 = IF(WordCount >= 4, PATHITEM(PathText, 4), "")
			VAR Cap1 = UPPER(LEFT(W1, 1)) & LOWER(MID(W1, 2, 100))
			VAR Cap2 = IF(W2 = "", "", UPPER(LEFT(W2, 1)) & LOWER(MID(W2, 2, 100)))
			VAR Cap3 = IF(W3 = "", "", UPPER(LEFT(W3, 1)) & LOWER(MID(W3, 2, 100)))
			VAR Cap4 = IF(W4 = "", "", UPPER(LEFT(W4, 1)) & LOWER(MID(W4, 2, 100)))
			RETURN
			TRIM(Cap1 & " " & Cap2 & " " & Cap3 & " " & Cap4)
		dataType: string
		displayFolder: Model
		lineageTag: 63a6102a-d972-4de6-9f47-8ce5adaeccb4
		summarizeBy: none

	partition repeat_purchase_odds_ratios = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\04ama\OneDrive\job-hunt\portfolio-projects\Ecommerce-growth-analytics\Dashboard\exports\repeat_purchase_odds_ratios.csv"), [Delimiter = ",", Columns = 8, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"feature", type text}, {"coefficient", type number}, {"odds_ratio", type number}, {"abs_coefficient", type number}, {"direction", type text}, {"model", type text}, {"run_at", type datetime}, {"git_commit", type text}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

