table step_funnel
	lineageTag: 0450f25f-ce4c-4427-ab9a-011f4ba3900b

	measure 'Step Conversion' = SUM(step_funnel[pct_moved_to_next])
		formatString: 0.00\%
		displayFolder: Funnel
		lineageTag: b1037c0b-6df5-4fb7-9539-312cf5164313

	measure 'Biggest Step Drop' =
			
			VAR MinRow = TOPN(1, ALL(step_funnel), step_funnel[pct_moved_to_next], 1)
			VAR FromRaw = MAXX(MinRow, step_funnel[from_stage])
			VAR ToRaw = MAXX(MinRow, step_funnel[to_stage])
			VAR FromLabel =
			    SWITCH(
			        TRUE(),
			        LOWER(FromRaw) = "created", "Purchased",
			        LOWER(FromRaw) = "approved", "Approved",
			        LOWER(FromRaw) = "shipped", "Shipped",
			        FromRaw
			    )
			VAR ToLabel =
			    SWITCH(
			        TRUE(),
			        LOWER(ToRaw) = "approved", "Approved",
			        LOWER(ToRaw) = "shipped", "Shipped",
			        LOWER(ToRaw) = "delivered", "Delivered",
			        ToRaw
			    )
			RETURN
			FromLabel & " → " & ToLabel
		displayFolder: Funnel
		lineageTag: 6efbccb8-b3b0-4014-ae34-38169aa2bd26

	measure 'Biggest Step Drop Pct' = MINX(ALL(step_funnel), step_funnel[pct_moved_to_next])
		formatString: 0.00\%
		displayFolder: Funnel
		lineageTag: bd9b28cd-e611-4ea2-b34f-8d6cadf587bc

	column from_stage
		dataType: string
		lineageTag: 1a36e0a8-5c3f-423c-a061-fd8e2dce7898
		summarizeBy: none
		sourceColumn: from_stage

		annotation SummarizationSetBy = Automatic

	column to_stage
		dataType: string
		lineageTag: ffb8edc9-4b5c-469f-8a3d-3af885c8e83b
		summarizeBy: none
		sourceColumn: to_stage

		annotation SummarizationSetBy = Automatic

	column from_count
		dataType: int64
		formatString: 0
		lineageTag: 9715971f-376a-4ab0-883d-cd5d1078b909
		summarizeBy: sum
		sourceColumn: from_count

		annotation SummarizationSetBy = Automatic

	column to_count
		dataType: int64
		formatString: 0
		lineageTag: 84bff563-4112-4d0e-a75f-8cc96aebb194
		summarizeBy: sum
		sourceColumn: to_count

		annotation SummarizationSetBy = Automatic

	column pct_moved_to_next
		dataType: double
		lineageTag: 22b71b91-a29c-49f9-a0c7-d9ee3a505630
		summarizeBy: sum
		sourceColumn: pct_moved_to_next

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition step_funnel = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\04ama\OneDrive\job-hunt\portfolio-projects\Ecommerce-growth-analytics\Dashboard\exports\step_funnel.csv"), [Delimiter = ",", Columns = 5, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"from_stage", type text}, {"to_stage", type text}, {"from_count", Int64.Type}, {"to_count", Int64.Type}, {"pct_moved_to_next", type number}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

