-- Q2: COHORT RETENTION
-- Group customers by the month of their FIRST order (their "cohort").
-- For each cohort, what % of customers placed another order in month 1, 2, 3... after that?
--
-- Tables: orders (order_id, customer_id, order_purchase_timestamp)
--
-- This is the hardest query in the project. Rough shape:
--   1. Find each customer's first order month  -> a CTE, using MIN() OVER (PARTITION BY customer_id)
--      or GROUP BY customer_id
--   2. For every order, compute months_since_first_order = difference between that order's
--      month and the customer's cohort month
--   3. Count distinct customers per (cohort_month, months_since_first_order)
--   4. Divide by the cohort's total size to get a retention %
--
-- Note: this Olist dataset is known to have very few repeat customers - a low/flat retention
-- curve is a real, correct finding here, not a bug. Say so plainly in the write-up.
--
-- TODO: write the cohort retention query here.
-- Expected output columns: cohort_month, months_since_first_order, customers_active, cohort_size, retention_pct
